Name=input("Enter the name")
print("My Name is:",Name)
Age=int(input("Enter the Age"))
print("Age is",Age)
Place=input("Enter the Location")
print("My native place is:",Place)
CollegeName=input("Enter the collegeName")
print("My college Name is:"+CollegeName)
Location=input("Enter the Location")
print("Location is ",Location)
CGPA=float(input("Enter CGPA"))
print("CGPA",CGPA)
Experiance=int(input("Enter the Experiance "))
print("My Experiance is",Experiance)
CompanyName=input("Enter the CompanyName")
print("Company name is",CompanyName)
salary=float(input("Enter the salary"))
print("Salary is ",salary)
